"use strict";
const D={N:[0,1],S:[0,-1],E:[1,0],W:[-1,0]},OP={N:"S",S:"N",E:"W",W:"E"},DIR=["N","S","E","W"],ROT=["RoN","RoS","RoE","RoW","RoL","RoR"],DIST={S:3,R:4,P:5},MAXPLY=64;
let NODE=0,SEL=0,STOP=0,DEADLINE=0,TT=new Map(),MC=new Map(),TC=new Map(),HIST=new Int32Array(8*64*10),CAPH=new Int32Array(8*64*10),CONT=new Map(),FOLLOW=new Map(),COUNTER=new Map(),KILL=[],UNDO=Array.from({length:MAXPLY+2},()=>new Int16Array(44)),REACH=null,ROOTRANK=new Map();
const GENUNDO=new Int16Array(44);
function pc(id){return id[0]}function sq(x,y){return y*8+x}function top(s,o){return s.top[o]}
function isRotation(item){return ROT.includes(item)}function itemBucket(item){if(item==="Pu")return"Pu";if(isRotation(item))return"Ro";if(item==="StS"||item==="StL")return"St";return null}function rotateIndex(s,o,item){if(item==="RoN")return s.roll[o][0];if(item==="RoS")return s.roll[o][1];if(item==="RoE")return s.roll[o][2];if(item==="RoW")return s.roll[o][3];if(item==="RoL")return s.rotL[o];if(item==="RoR")return s.rotR[o];return o}
function key(s){return s.side+"|"+s.c.W+","+s.c.B+"|q"+s.q.W+","+s.q.B+"|r"+s.rem+"|"+[s.it.W.Pu,s.it.W.Ro,s.it.W.St,s.it.B.Pu,s.it.B.Ro,s.it.B.St].join(",")+"|"+s.p.map(p=>p.a?(p.x+8*p.y)+"/"+s.red[p.o]:"x").join(";")}
function adj(s,x,y,side,skip){let a=[];for(let i=0;i<8;i++){let p=s.p[i];if(i===skip||!p.a||pc(p.id)===side)continue;if(Math.abs(p.x-x)+Math.abs(p.y-y)===1)a.push(i)}return a}
function occ(s,x,y,skip){for(let i=0;i<8;i++){let p=s.p[i];if(i!==skip&&p.a&&p.x===x&&p.y===y)return 1}return 0}
function fight(a,b){if(a===b)return 0;if((a==="S"&&b==="P")||(a==="R"&&b==="S")||(a==="P"&&b==="R"))return 1;return-1}
function initPieces(s){for(let i=0;i<8;i++){let p=s.p[i],w=i<4,g=["S","R","P","S"][i%4],st=w?[[0,0],[2,0],[4,0],[6,0]][i]:[[7,7],[5,7],[3,7],[1,7]][i-4];p.a=1;p.x=st[0];p.y=st[1];p.o=s.canon[g+(w?"S":"N")]}}
function saveState(s,u){u[0]=s.side==="W"?0:1;u[1]=s.c.W;u[2]=s.c.B;u[3]=s.it.W.Pu;u[4]=s.it.W.Ro;u[5]=s.it.W.St;u[6]=s.it.B.Pu;u[7]=s.it.B.Ro;u[8]=s.it.B.St;for(let i=0;i<8;i++){let p=s.p[i],j=9+4*i;u[j]=p.a;u[j+1]=p.x;u[j+2]=p.y;u[j+3]=p.o}u[41]=s.q.W;u[42]=s.q.B;u[43]=s.rem}
function restoreState(s,u){s.side=u[0]===0?"W":"B";s.c.W=u[1];s.c.B=u[2];s.it.W.Pu=u[3];s.it.W.Ro=u[4];s.it.W.St=u[5];s.it.B.Pu=u[6];s.it.B.Ro=u[7];s.it.B.St=u[8];for(let i=0;i<8;i++){let p=s.p[i],j=9+4*i;p.a=u[j];p.x=u[j+1];p.y=u[j+2];p.o=u[j+3]}s.q.W=u[41];s.q.B=u[42];s.rem=u[43]}
function saveUndo(s,slot){saveState(s,UNDO[slot])}function restoreUndo(s,slot){restoreState(s,UNDO[slot])}
function doMoveWithUndo(s,m,u){saveState(s,u);let p=s.p[m.i],o=rotateIndex(s,p.o,m.item),b=itemBucket(m.item);if(b)s.it[s.side][b]--;for(let d of m.dirs)o=s.roll[o][DIR.indexOf(d)];let z=m.path[m.path.length-1];p.x=z[0];p.y=z[1];p.o=o;let es=adj(s,p.x,p.y,s.side,m.i);if(es.length===1){let e=s.p[es[0]],f=fight(top(s,p.o),top(s,e.o));if(f!==0){let lose=f>0?e:p,winner=f>0?s.side:(s.side==="W"?"B":"W");lose.a=0;s.c[winner]++}}let wa=s.p.slice(0,4).some(p=>p.a),ba=s.p.slice(4).some(p=>p.a),reset=!wa||!ba;if(reset)initPieces(s);s.side=s.side==="W"?"B":"W";if(s.rem>0)s.rem--;return reset}
function doMove(s,m,slot){doMoveWithUndo(s,m,UNDO[slot])}
function generateMoves(s){let raw=[];for(let i=0;i<8;i++){let p=s.p[i];if(!p.a||pc(p.id)!==s.side)continue;let variants=[{item:null,push:null,o:p.o,start:[p.x,p.y],L:DIST[top(s,p.o)],last:null}];if(s.it[s.side].Pu>0){for(let d of DIR){let [dx,dy]=D[d],x=p.x+dx,y=p.y+dy;if(x>=0&&x<8&&y>=0&&y<8&&!occ(s,x,y,i))variants.push({item:"Pu",push:[x,y],o:p.o,start:[x,y],L:DIST[top(s,p.o)],last:null})}}if(s.it[s.side].Ro>0){for(let item of ROT){let ro=rotateIndex(s,p.o,item);variants.push({item,push:null,o:ro,start:[p.x,p.y],L:DIST[top(s,ro)],last:null})}}if(s.it[s.side].St>0){let L=DIST[top(s,p.o)];variants.push({item:"StS",push:null,o:p.o,start:[p.x,p.y],L:L-1,last:null},{item:"StL",push:null,o:p.o,start:[p.x,p.y],L:L+1,last:null})}for(let v of variants){let path=[[p.x,p.y]],dirs=[];function dfs(x,y,o,last,n){if(n===v.L){raw.push({i,id:p.id,item:v.item,push:v.push?v.push.slice():null,path:path.slice(),dirs:dirs.slice()});return}for(let d of DIR){if(last&&d===OP[last])continue;let [dx,dy]=D[d],nx=x+dx,ny=y+dy;if(nx<0||nx>7||ny<0||ny>7||occ(s,nx,ny,i))continue;if(n+1===v.L&&adj(s,nx,ny,s.side,i).length>=2)continue;path.push([nx,ny]);dirs.push(d);dfs(nx,ny,s.roll[o][DIR.indexOf(d)],d,n+1);dirs.pop();path.pop()}}dfs(v.start[0],v.start[1],v.o,v.last,0)}}return raw}
let PARTIAL_RED=null;function partialKey(s,x,y,o,remaining,last){if(!PARTIAL_RED)PARTIAL_RED=s.red.map(r=>s.red.indexOf(r));return sq(x,y)|(PARTIAL_RED[o]<<6)|(remaining<<11)|((last?DIR.indexOf(last):4)<<14)}function tacticalReach(s){let r=Array.from({length:7},()=>new Uint8Array(64));for(let i=0;i<8;i++){let p=s.p[i];if(!p.a||pc(p.id)===s.side)continue;for(let d of DIR){let[dx,dy]=D[d],x=p.x+dx,y=p.y+dy;if(x>=0&&x<8&&y>=0&&y<8)r[0][sq(x,y)]=1}}for(let n=1;n<=6;n++)for(let y=0;y<8;y++)for(let x=0;x<8;x++){for(let d of DIR){let[dx,dy]=D[d],nx=x+dx,ny=y+dy;if(nx>=0&&nx<8&&ny>=0&&ny<8&&r[n-1][sq(nx,ny)]){r[n][sq(x,y)]=1;break}}}return r}
function searchMoves(s,tacticalOnly=false){let cache=tacticalOnly?TC:MC,ck=key(s),cached=cache.get(ck);if(cached)return cached;let reach=tacticalOnly?tacticalReach(s):null,out=[],finalSeen=new Set(),mover=s.side,opp=mover==="W"?"B":"W",own=s.c[mover],enemy=s.c[opp];for(let i=0;i<8;i++){let p=s.p[i];if(!p.a||pc(p.id)!==s.side)continue;let variants=[{item:null,push:null,o:p.o,start:[p.x,p.y],L:DIST[top(s,p.o)],last:null}];if(s.it[s.side].Pu>0)for(let d of DIR){let [dx,dy]=D[d],x=p.x+dx,y=p.y+dy;if(x>=0&&x<8&&y>=0&&y<8&&!occ(s,x,y,i))variants.push({item:"Pu",push:[x,y],o:p.o,start:[x,y],L:DIST[top(s,p.o)],last:null})}if(s.it[s.side].Ro>0){let seenRo=new Set;for(let item of ROT){let ro=rotateIndex(s,p.o,item),rk=s.red[ro];if(seenRo.has(rk))continue;seenRo.add(rk);variants.push({item,push:null,o:ro,start:[p.x,p.y],L:DIST[top(s,ro)],last:null})}}if(s.it[s.side].St>0){let L=DIST[top(s,p.o)];variants.push({item:"StS",push:null,o:p.o,start:[p.x,p.y],L:L-1,last:null},{item:"StL",push:null,o:p.o,start:[p.x,p.y],L:L+1,last:null})}for(let v of variants){let path=[[p.x,p.y]],dirs=[],partialSeen=new Set([partialKey(s,v.start[0],v.start[1],v.o,v.L,v.last)]);function dfs(x,y,o,last,remaining){if(tacticalOnly&&remaining<=6&&!reach[remaining][sq(x,y)])return;if(remaining===0){if(tacticalOnly){let es=adj(s,x,y,s.side,i);if(es.length!==1||fight(top(s,o),top(s,s.p[es[0]].o))===0)return}let m={i,id:p.id,item:v.item,push:v.push?v.push.slice():null,path:path.slice(),dirs:dirs.slice()};let reset=doMoveWithUndo(s,m,GENUNDO);let k=key(s),t=(s.c[mover]-own)-(s.c[opp]-enemy);restoreState(s,GENUNDO);if((!tacticalOnly||t!==0)&&!finalSeen.has(k)){finalSeen.add(k);out.push({m,t,reset})}return}for(let d of DIR){if(last&&d===OP[last])continue;let [dx,dy]=D[d],nx=x+dx,ny=y+dy;if(nx<0||nx>7||ny<0||ny>7||occ(s,nx,ny,i))continue;if(remaining===1&&adj(s,nx,ny,s.side,i).length>=2)continue;let no=s.roll[o][DIR.indexOf(d)],pk=partialKey(s,nx,ny,no,remaining-1,d);if(partialSeen.has(pk))continue;partialSeen.add(pk);path.push([nx,ny]);dirs.push(d);dfs(nx,ny,no,d,remaining-1);dirs.pop();path.pop()}}dfs(v.start[0],v.start[1],v.o,v.last,v.L)}}cache.set(ck,out);if(cache.size>80000)cache.clear();return out}
function uniqueMoves(s){return searchMoves(s,false)}
function tacticalMoves(s){return searchMoves(s,true)}
function cloneState(s){return{side:s.side,c:{W:s.c.W,B:s.c.B},q:{W:s.q.W,B:s.q.B},rem:s.rem,it:{W:{Pu:s.it.W.Pu,Ro:s.it.W.Ro,St:s.it.W.St},B:{Pu:s.it.B.Pu,Ro:s.it.B.Ro,St:s.it.B.St}},p:s.p.map(p=>({...p})),roll:s.roll,rotL:s.rotL,rotR:s.rotR,top:s.top,red:s.red,canon:s.canon}}
function ensureReach(s){if(REACH)return;let reds=[...new Set(s.red)],rid=new Map(reds.map((x,i)=>[x,i])),marks=new Uint16Array(64*reds.length),gen=0,profiles=new Uint16Array(64*24*4);function nextGen(){gen++;if(gen>65534){marks.fill(0);gen=1}return gen}function family(parts){let g=nextGen(),count=0;function mark(x,y,o){let k=sq(x,y)*reds.length+rid.get(s.red[o]);if(marks[k]!==g){marks[k]=g;count++}}function dfs(x,y,o,last,rem){if(rem===0){mark(x,y,o);return}for(let d of DIR){if(last&&d===OP[last])continue;let [dx,dy]=D[d],nx=x+dx,ny=y+dy;if(nx<0||nx>7||ny<0||ny>7)continue;dfs(nx,ny,s.roll[o][DIR.indexOf(d)],d,rem-1)}}for(let p of parts)dfs(p.x,p.y,p.o,p.last||null,p.L);return count}for(let y=0;y<8;y++)for(let x=0;x<8;x++)for(let o=0;o<24;o++){let b0=(sq(x,y)*24+o)*4,previous=s.red.indexOf(s.red[o]);if(previous<o){let bp=(sq(x,y)*24+previous)*4;for(let k=0;k<4;k++)profiles[b0+k]=profiles[bp+k];continue}let L=DIST[top(s,o)],normal=[{x,y,o,L,last:null}],push=normal.slice(),rotation=normal.slice(),step=normal.slice();for(let d of DIR){let [dx,dy]=D[d],px=x+dx,py=y+dy;if(px>=0&&px<8&&py>=0&&py<8)push.push({x:px,y:py,o,L,last:null})}for(let item of ROT){let ro=rotateIndex(s,o,item);rotation.push({x,y,o:ro,L:DIST[top(s,ro)],last:null})}step.push({x,y,o,L:L-1,last:null},{x,y,o,L:L+1,last:null});let b=(sq(x,y)*24+o)*4;profiles[b]=family(normal);profiles[b+1]=family(push);profiles[b+2]=family(rotation);profiles[b+3]=family(step)}REACH=profiles}
function reachValue(s,p,f){ensureReach(s);return REACH[(sq(p.x,p.y)*24+p.o)*4+f]}
function inventoryValue(s,side,reserve){let names=["Pu","Ro","St"],v=0;for(let b=0;b<3;b++){let n=s.it[side][names[b]]||0;if(!n)continue;v+=reserve*n;let best=0;for(let i=0;i<8;i++){let p=s.p[i];if(!p.a||pc(p.id)!==side)continue;best=Math.max(best,reachValue(s,p,b+1)-reachValue(s,p,0))}let latent=Math.min(9,Math.floor(best/10));if(reserve)v+=Math.floor(latent*reserve/6)}return v}
function mobility1(s,i){let p=s.p[i],n=0;if(!p.a)return 0;for(let d of DIR){let [dx,dy]=D[d],x=p.x+dx,y=p.y+dy;if(x>=0&&x<8&&y>=0&&y<8&&!occ(s,x,y,i))n++}return n}
function mobility2(s,i){let p=s.p[i],n=0;if(!p.a)return 0;for(let d of DIR){let [dx,dy]=D[d],x=p.x+dx,y=p.y+dy;if(x<0||x>7||y<0||y>7||occ(s,x,y,i))continue;for(let e of DIR){if(e===OP[d])continue;let [ex,ey]=D[e],xx=x+ex,yy=y+ey;if(xx>=0&&xx<8&&yy>=0&&yy<8&&!occ(s,xx,yy,i))n++}}return n}
function hasItems(s){return s.it.W.Pu||s.it.W.Ro||s.it.W.St||s.it.B.Pu||s.it.B.Ro||s.it.B.St}
function terminalW(s){let d=(s.q.W+2*s.c.W)-(s.q.B+2*s.c.B);if(d)return 100*d;let qd=s.q.W-s.q.B;return qd>0?25:qd<0?-25:0}function evalW(s){if(s.rem===0)return terminalW(s);ensureReach(s);let v=100*((s.q.W+2*s.c.W)-(s.q.B+2*s.c.B)),aw=0,ab=0;for(let i=0;i<8;i++){let p=s.p[i];if(!p.a)continue;i<4?aw++:ab++;let mob=2*mobility1(s,i)+Math.floor(mobility2(s,i)/2)+Math.floor(reachValue(s,p,0)/20);v+=(i<4?1:-1)*mob}let itemV=s.rem<0?6:Math.max(0,Math.min(6,2+s.rem));return v+12*(aw-ab)+inventoryValue(s,"W",itemV)-inventoryValue(s,"B",itemV)}function ev(s){let v=evalW(s);return s.side==="W"?v:-v}
function stop(){NODE++;if((NODE&255)===0&&performance.now()>DEADLINE)STOP=1;return STOP}
function same(a,b){if(!a||!b||a.i!==b.i||(a.item||null)!==(b.item||null)||a.path.length!==b.path.length)return 0;let ap=a.push,bp=b.push;if(!!ap!==!!bp)return 0;if(ap&&(ap[0]!==bp[0]||ap[1]!==bp[1]))return 0;for(let i=0;i<a.path.length;i++)if(a.path[i][0]!==b.path[i][0]||a.path[i][1]!==b.path[i][1])return 0;return 1}
function excluded(m,list){return list.some(x=>same(m,x))}
function itemIndex(item){if(!item)return 0;if(item==="Pu")return 1;if(item==="RoN")return 2;if(item==="RoS")return 3;if(item==="RoE")return 4;if(item==="RoW")return 5;if(item==="RoL")return 6;if(item==="RoR")return 7;if(item==="StS")return 8;return 9}
function moveSlot(m){let z=m.path.at(-1);return((m.i*64+sq(z[0],z[1]))*10)+itemIndex(m.item)}
function pairKey(a,b){return a*(8*64*10)+b}
function boundedAdd(arr,i,d){let v=arr[i]+d;if(v>100000||v<-100000)v=Math.trunc(v/2);arr[i]=v}
function sparseScore(map,k){return map.get(k)||0}
function sparseAdd(map,k,d){let v=(map.get(k)||0)+d;if(v>100000||v<-100000)v=Math.trunc(v/2);map.set(k,v);if(map.size>250000)map.clear()}
function captureHistoryScore(m){return Math.trunc(CAPH[moveSlot(m)]/4)}
function killerScore(m,ply){let k=KILL[ply];if(!k)return 0;if(k[0]&&same(m,k[0]))return 200000;if(k[1]&&same(m,k[1]))return 150000;return 0}
function pressure(s){let n=0;for(let x of tacticalMoves(s))if(x.t>0&&++n>=4)break;return n}
function pressureFor(s,side){if(s.side===side)return pressure(s);let old=s.side;s.side=side;let n=pressure(s);s.side=old;return n}
function historyScore(m,prev,prev2){let b=moveSlot(m),v=HIST[b];if(prev){let a=moveSlot(prev);v+=Math.trunc(sparseScore(CONT,pairKey(a,b))/2);let c=COUNTER.get(a);if(c&&same(m,c))v+=120000}if(prev2){let a=moveSlot(prev2);v+=Math.trunc(sparseScore(FOLLOW,pairKey(a,b))/4)}return v}
function recordQuiet(m,d,ply,prev,prev2,tried){let b=moveSlot(m),bonus=Math.max(1,d*d);boundedAdd(HIST,b,bonus);if(prev){let a=moveSlot(prev);sparseAdd(CONT,pairKey(a,b),2*bonus);COUNTER.set(a,m);if(COUNTER.size>16384)COUNTER.clear()}if(prev2){let a=moveSlot(prev2);sparseAdd(FOLLOW,pairKey(a,b),bonus)}let pen=Math.max(1,Math.trunc(bonus/2));for(let q of tried){if(same(q,m))continue;let qb=moveSlot(q);boundedAdd(HIST,qb,-pen);if(prev)sparseAdd(CONT,pairKey(moveSlot(prev),qb),-pen);if(prev2)sparseAdd(FOLLOW,pairKey(moveSlot(prev2),qb),-Math.max(1,Math.trunc(pen/2)))}if(!KILL[ply])KILL[ply]=[null,null];if(!same(m,KILL[ply][0])){KILL[ply][1]=KILL[ply][0];KILL[ply][0]=m}}
function recordTactical(m,d){boundedAdd(CAPH,moveSlot(m),Math.max(1,2*d*d))}
function q(s,a,b,ply){SEL=Math.max(SEL,ply);if(s.rem===0||ply>=MAXPLY||stop())return ev(s);if(s.rem===1){let ms=uniqueMoves(s);if(!ms.length)return ev(s);for(let x of ms){if(stop())return a;doMove(s,x.m,ply);let v=-ev(s);restoreUndo(s,ply);SEL=Math.max(SEL,ply+1);if(v>=b)return b;if(v>a)a=v}return a}let st=ev(s);if(st>=b)return b;if(st>a)a=st;let ms=tacticalMoves(s).filter(x=>x.t>=0||x.reset).sort((x,y)=>(y.t*100000+captureHistoryScore(y.m))-(x.t*100000+captureHistoryScore(x.m)));for(let x of ms){doMove(s,x.m,ply);let sc=-q(s,-b,-a,ply+1);restoreUndo(s,ply);if(STOP)return a;if(sc>=b){recordTactical(x.m,1);return b}if(sc>a)a=sc}return a}
function ab(s,d,a,b,ply,pv,prev,prev2,extUsed=0){
  SEL=Math.max(SEL,ply);if(s.rem===0||ply>=MAXPLY)return ev(s);if(d<=0)return q(s,a,b,ply);if(stop())return ev(s);
  let st0=ev(s);if(!pv&&d<=4){if(st0-(60+30*d)>=b)return st0;if(d===1&&st0+70<=a)return q(s,a,b,ply)}let mover=s.side,k=key(s),e=TT.get(k),tm=e&&e.m,oa=a,ob=b;if(e&&e.d>=d&&!pv){if(e.bd===0)return e.v;if(e.bd===1&&e.v>=b)return e.v;if(e.bd===-1&&e.v<=a)return e.v}
  let ms=uniqueMoves(s);if(!ms.length)return ev(s);let ownBefore=0;for(let x of ms)if(x.t>0&&++ownBefore>=4)break;let oppBefore=null;
  let ord=ms.map(x=>({x,sc:(tm&&same(x.m,tm)?1000000:0)+(x.t>0?500000+x.t*10000+captureHistoryScore(x.m):x.t<0?-250000+captureHistoryScore(x.m):0)+killerScore(x.m,ply)+historyScore(x.m,prev,prev2)})).sort((x,y)=>y.sc-x.sc),bm=null,j=0,quiets=[];
  for(let z of ord){let x=z.x,sc;doMove(s,x.m,ply);let extend=x.t!==0&&extUsed<1,nextExt=extUsed+(extend?1:0),childDepth=d-1+(extend?1:0);
    if(j===0)sc=-ab(s,childDepth,-b,-a,ply+1,pv,x.m,prev,nextExt);else{
      let hv=historyScore(x.m,prev,prev2),known=(prev&&COUNTER.get(moveSlot(prev))&&same(x.m,COUNTER.get(moveSlot(prev))))||killerScore(x.m,ply)>0||hv>4*d*d,red=!pv&&x.t===0&&d>=4&&j>=4&&!known,r=1;
      if(red){if(oppBefore===null)oppBefore=pressureFor(s,mover==="W"?"B":"W");let oppAfter=oppBefore>0?pressure(s):0,ownAfter=ownBefore<4?pressureFor(s,mover):ownBefore,defensive=oppBefore>0&&oppAfter<oppBefore,creates=ownAfter>ownBefore;if(defensive||creates)red=0;else if(!x.m.item&&-ev(s)<st0+8&&d>=7&&j>=10&&hv<=0)r=2}
       if(red){sc=-ab(s,Math.max(0,childDepth-r),-a-1,-a,ply+1,0,x.m,prev,nextExt);if(sc>a)sc=-ab(s,childDepth,-a-1,-a,ply+1,0,x.m,prev,nextExt)}else sc=-ab(s,childDepth,-a-1,-a,ply+1,0,x.m,prev,nextExt);
       if(sc>a&&sc<b)sc=-ab(s,childDepth,-b,-a,ply+1,pv,x.m,prev,nextExt)
    }
     restoreUndo(s,ply);j++;if(x.t===0)quiets.push(x.m);if(STOP)return a;if(sc>a){a=sc;bm=x.m}if(a>=b){if(x.t===0)recordQuiet(x.m,d,ply,prev,prev2,quiets);else recordTactical(x.m,d);break}
  }
  let bd=a<=oa?-1:a>=ob?1:0;TT.set(k,{d,v:a,bd,m:bm});if(TT.size>150000)TT.clear();return a
}
function pvline(s,best,d){let x=cloneState(s),out=[],m=best;for(let i=0;i<Math.min(MAXPLY,d+4)&&m;i++){out.push(m);doMove(x,m,i);let e=TT.get(key(x));m=e&&e.m}return out}
function actionFamily(m){if(!m.item)return 0;if(m.item==="Pu")return 1;if(isRotation(m.item))return 2;return 3}function moveSig(m){return JSON.stringify(m)}function rootPrior(m){let v=ROOTRANK.get(moveSig(m));return Number.isFinite(v)?1000*v:0}function installRootRanking(lines){ROOTRANK=new Map((lines||[]).map(x=>[moveSig(x.move),x.value]))}
function rootPass(s,roots,preferred,d,a,b,skip,multi=false){let ord=roots.filter(x=>!excluded(x.m,skip)).map(x=>({x,sc:(same(x.m,preferred)?1200000:0)+(x.t>0?500000+x.t*10000+captureHistoryScore(x.m):x.t<0?-250000+captureHistoryScore(x.m):0)+historyScore(x.m,null,null)+rootPrior(x.m)})).sort((x,y)=>y.sc-x.sc);if(!ord.length)return{best:null,value:-1e9,scores:[]};let best=ord[0].x.m,bv=-1e9,j=0,alpha=a,scores=[],fam=[0,0,0,0];for(let z of ord){let x=z.x,v,extend=x.t!==0,ext=extend?1:0,childDepth=d-1+(extend?1:0),fi=actionFamily(x.m),fidx=fam[fi]++,mi=j++;doMove(s,x.m,0);if(mi===0)v=-ab(s,childDepth,-b,-alpha,1,1,x.m,null,ext);else{let quota=fi===0?32:24,reduce=!multi&&d>=3&&x.t===0&&fidx>=quota&&mi>=64;if(reduce){v=-ab(s,Math.max(0,childDepth-1),-alpha-1,-alpha,1,0,x.m,null,ext);if(v>alpha)v=-ab(s,childDepth,-alpha-1,-alpha,1,0,x.m,null,ext)}else v=-ab(s,childDepth,-alpha-1,-alpha,1,0,x.m,null,ext);if(v>alpha&&v<b)v=-ab(s,childDepth,-b,-alpha,1,1,x.m,null,ext)}restoreUndo(s,0);if(STOP)break;scores.push({move:x.m,value:v});if(v>bv){bv=v;best=x.m}if(v>alpha)alpha=v;if(alpha>=b)break}return{best,value:bv,scores}}
function search(s,lim,progress){
  let start=performance.now();NODE=0;SEL=0;STOP=0;DEADLINE=start+(lim.ms||1000);
  KILL=Array.from({length:MAXPLY},()=>[null,null]);
  if(TT.size>150000)TT.clear();if(MC.size>80000)MC.clear();if(TC.size>80000)TC.clear();
  ensureReach(s);
  let roots=s.rem===0?[]:uniqueMoves(s),k=Math.min(roots.length,Math.max(1,Math.min(3,lim.multipv||1)));
  let seed=lim.seedResult,validSeed=seed&&seed.depth>0&&seed.candidates?.length>=k&&seed.candidates.slice(0,k).every(c=>roots.some(x=>same(x.m,c.move)));
  let prev=validSeed?seed.best:roots[0]?.m,prevValue=validSeed?seed.value:0;
  let res=validSeed?{...seed,candidates:seed.candidates.slice(0,k)}:{best:prev||null,value:ev(s),depth:0,seldepth:0,nodes:0,pv:prev?[prev]:[],candidates:[],rootRanking:[]};
  installRootRanking(validSeed?seed.rootRanking||seed.candidates:[]);
  for(let d=validSeed?Math.max(1,lim.startDepth||seed.depth+1):1;d<=Math.min(MAXPLY,lim.depth||64)&&prev;d++){
    let pass,w=50,a=d>=4?prevValue-w:-1e9,b=d>=4?prevValue+w:1e9;
    while(true){pass=rootPass(s,roots,prev,d,a,b,[],k>1);if(STOP||!pass.best)break;
      if(pass.value<=a){w*=2;a=prevValue-w;b=prevValue+w;continue}
      if(pass.value>=b){w*=2;a=prevValue-w;b=prevValue+w;continue}break}
    if(STOP||!pass.best)break;
    let lines=[{move:pass.best,value:pass.value,pv:pvline(s,pass.best,d)}],skip=[pass.best];
    let ranking=pass.scores.slice().sort((a,b)=>b.value-a.value),secondaryRoots=[];
    if(ranking.length){let limit=Math.min(24,ranking.length),cutoff=ranking[limit-1].value;for(let line of ranking)if(line.value>=cutoff){let r=roots.find(x=>same(x.m,line.move));if(r)secondaryRoots.push(r)}}
    for(let oldLine of(res.candidates||[])){let r=roots.find(x=>same(x.m,oldLine.move));if(r&&!secondaryRoots.some(x=>same(x.m,r.m)))secondaryRoots.push(r)}
    for(let rank=1;rank<k;rank++){
      let next=rootPass(s,secondaryRoots.length?secondaryRoots:roots,res.candidates[rank]?.move,d,-1e9,1e9,skip,true);
      if(STOP||!next.best)break;
      lines.push({move:next.best,value:next.value,pv:pvline(s,next.best,d)});skip.push(next.best)
    }
    if(STOP||lines.length!==k)break;
    lines.sort((a,b)=>b.value-a.value);prev=lines[0].move;prevValue=lines[0].value;
    installRootRanking(ranking);
    res={best:prev,value:prevValue,depth:d,seldepth:SEL,nodes:NODE,pv:lines[0].pv,candidates:lines,rootRanking:ranking.slice(0,96),ms:Math.max(1,performance.now()-start)};
    if(progress)progress(res);if(s.rem>0&&d>=s.rem)break
  }
  res.nodes=NODE;res.seldepth=SEL;res.ms=Math.max(1,performance.now()-start);return res
}
function searchSeedFromCandidate(c){return c?.search||null}
function candidateSeed(lim,pred){let old=lim.seedResult?.candidates?.find(pred);return searchSeedFromCandidate(old)}
function runItemProbe(s,chooser,name,ms,lim,seed){let x=cloneState(s);x.it[chooser][name]++;x.side="W";let r=search(x,{depth:lim.depth||64,ms:Math.max(120,ms),multipv:1,startDepth:seed?seed.depth+1:1,seedBest:seed?.best||null,seedValue:seed?.value,seedResult:seed||null});return{item:name,value:r.value,depth:r.depth,seldepth:r.seldepth,nodes:r.nodes,ms:r.ms,best:r.best,pv:r.pv,search:r}}
function chooseItem(s,chooser,lim,progress){let names=["Pu","Ro","St"],lines=[],start=performance.now(),total=Math.max(900,lim.ms||10000),screen=Math.max(160,Math.trunc(total*.15));let snapshot=()=>({decision:"item",chooser,bestItem:lines[0]?.item||null,value:lines[0]?.value||0,candidates:lines.map(x=>({...x})),ms:Math.max(1,performance.now()-start)});for(let name of names){let seed=candidateSeed(lim,c=>c.item===name);lines.push(runItemProbe(s,chooser,name,screen,lim,seed))}let cmp=(a,b)=>{let d=chooser==="W"?b.value-a.value:a.value-b.value;return d||names.indexOf(a.item)-names.indexOf(b.item)};lines.sort(cmp);if(progress)progress(snapshot());let refine=[.25,.18,.12];for(let rank=0;rank<3;rank++){let c=lines[rank],seed=searchSeedFromCandidate(c),ms=Math.max(140,Math.trunc(total*refine[rank]));lines[rank]=runItemProbe(s,chooser,c.item,ms,lim,seed);lines.sort(cmp);if(progress)progress(snapshot())}lines.sort(cmp);return snapshot()}
function runInitialProbe(s,first,name,ms,lim,seed){let x=cloneState(s),role=first?"W":"B";x.it[role][name]++;x.q={W:first?1:0,B:first?0:1};x.side="W";let r=search(x,{depth:lim.depth||64,ms:Math.max(100,ms),multipv:1,startDepth:seed?seed.depth+1:1,seedBest:seed?.best||null,seedValue:seed?.value,seedResult:seed||null}),chooserValue=first?r.value:-r.value;return{first,item:name,value:chooserValue,whiteValue:r.value,depth:r.depth,seldepth:r.seldepth,nodes:r.nodes,ms:r.ms,best:r.best,pv:r.pv,search:r}}
function chooseInitial(s,lim,progress){let names=["Pu","Ro","St"],lines=[],start=performance.now(),total=Math.max(1400,lim.ms||10000),screen=Math.max(100,Math.trunc(total*.08));let cmp=(a,b)=>(b.value-a.value)||(a.first===b.first?names.indexOf(a.item)-names.indexOf(b.item):(a.first?-1:1));let snapshot=()=>({decision:"initial",bestFirst:lines[0]?.first??true,bestItem:lines[0]?.item||null,value:lines[0]?.value||0,candidates:lines.map(x=>({...x})),ms:Math.max(1,performance.now()-start)});for(let first of[true,false])for(let name of names){let seed=candidateSeed(lim,c=>c.first===first&&c.item===name);lines.push(runInitialProbe(s,first,name,screen,lim,seed))}lines.sort(cmp);if(progress)progress(snapshot());let refine=[.24,.16,.12];for(let rank=0;rank<3;rank++){let c=lines[rank],seed=searchSeedFromCandidate(c),ms=Math.max(120,Math.trunc(total*refine[rank]));lines[rank]=runInitialProbe(s,c.first,c.item,ms,lim,seed);lines.sort(cmp);if(progress)progress(snapshot())}lines.sort(cmp);return snapshot()}
onmessage=e=>{let {id,state,limits,kind,chooser}=e.data;try{if(kind==="item"){let result=chooseItem(state,chooser,limits||{},r=>postMessage({id,result:r,partial:true}));postMessage({id,result,partial:false});return}if(kind==="initial"){let result=chooseInitial(state,limits||{},r=>postMessage({id,result:r,partial:true}));postMessage({id,result,partial:false});return}let result=search(state,limits,r=>postMessage({id,result:r,partial:true}));postMessage({id,result,partial:false})}catch(err){postMessage({id,error:String(err&&err.message||err)})}};