#include "evaluate.h"
#include <algorithm>
#include <array>
#include <cstdint>
#include <utility>
namespace rpsc {namespace {
constexpr Value BaseItemReserve=6;constexpr int ReducedStateCount=27;constexpr std::array<std::pair<int,int>,4>Delta{{{0,1},{0,-1},{1,0},{-1,0}}};constexpr std::array<Direction,4>Dir{{Direction::North,Direction::South,Direction::East,Direction::West}};
Direction opposite_dir(Direction d){return d==Direction::North?Direction::South:d==Direction::South?Direction::North:d==Direction::East?Direction::West:Direction::East;}
struct ReachProfile{std::uint16_t normal=0,push=0,rotation=0,step=0;};using ReachTable=std::array<std::array<ReachProfile,24>,64>;using Marks=std::array<bool,64*ReducedStateCount>;
void collect(int f,int r,Orientation o,int rem,bool has,Direction last,Marks&m){auto&t=OrientationTable::instance();if(!rem){int st=t.gesture_state_id(o);m[std::size_t(make_square(f,r))*ReducedStateCount+std::size_t(st)]=true;return;}for(int i=0;i<4;++i){auto d=Dir[i];if(has&&d==opposite_dir(last))continue;int nf=f+Delta[i].first,nr=r+Delta[i].second;if(!valid_square(nf,nr))continue;collect(nf,nr,t.roll(o,d),rem-1,true,d,m);}}
void add(Square s,Orientation o,int rolls,Marks&m){collect(file_of(s),rank_of(s),o,rolls,false,Direction::North,m);}std::uint16_t count(const Marks&m){return std::uint16_t(std::count(m.begin(),m.end(),true));}
ReachTable build(){ReachTable out{};auto&t=OrientationTable::instance();for(int si=0;si<64;++si)for(int oi=0;oi<24;++oi){Square s=Square(si);Orientation o=Orientation(oi);int b=base_roll_length(t.top_gesture(o));Marks n{};add(s,o,b,n);Marks p=n;for(auto[df,dr]:Delta){int f=file_of(s)+df,r=rank_of(s)+dr;if(valid_square(f,r))add(make_square(f,r),o,b,p);}Marks ro=n;add(s,t.rotate_left(o),b,ro);add(s,t.rotate_right(o),b,ro);Marks st=n;add(s,o,b-1,st);add(s,o,b+1,st);out[si][oi]={count(n),count(p),count(ro),count(st)};}return out;}const ReachTable&table(){static const ReachTable t=build();return t;}const ReachProfile&reach(const PieceState&p){return table()[std::size_t(p.square)][std::size_t(p.orientation)];}
int first_mob(const Position&p,PieceId id){auto&pc=p.piece(id);if(!pc.alive())return 0;int c=0;for(auto[df,dr]:Delta){int f=file_of(pc.square)+df,r=rank_of(pc.square)+dr;if(valid_square(f,r)&&!p.occupied(make_square(f,r),id))++c;}return c;}
int second_mob(const Position&p,PieceId id){auto&pc=p.piece(id);if(!pc.alive())return 0;int c=0;for(auto[df,dr]:Delta){int f=file_of(pc.square)+df,r=rank_of(pc.square)+dr;if(!valid_square(f,r)||p.occupied(make_square(f,r),id))continue;for(auto[ef,er]:Delta){if(ef==-df&&er==-dr)continue;int sf=f+ef,sr=r+er;if(valid_square(sf,sr)&&!p.occupied(make_square(sf,sr),id))++c;}}return c;}
Value terminal(const Position&p){int s=p.score(Color::White)-p.score(Color::Black);if(s)return ScoreUnit*s;int q=p.quiz(Color::White)-p.quiz(Color::Black);return q>0?ScoreUnit/4:q<0?-ScoreUnit/4:0;}
int reserve(const Position&p){int r=p.remaining_board_plies();if(r<0)return BaseItemReserve;return std::max(0,std::min<int>(BaseItemReserve,2+r));}int added(const ReachProfile&r,int b){return b==0?int(r.push)-int(r.normal):b==1?int(r.rotation)-int(r.normal):int(r.step)-int(r.normal);}int inventory(const Position&p,Color side,int rv){int v=0;for(int b=0;b<3;++b){int n=p.item_count(side,b);if(n<=0)continue;v+=rv*n;int best=0;for(int i=0;i<PieceCount;++i){auto id=PieceId(i);if(piece_color(id)==side&&p.piece(id).alive())best=std::max(best,added(reach(p.piece(id)),b));}int latent=std::min(9,best/10);if(rv)v+=latent*rv/BaseItemReserve;}return v;}
}
Value evaluate_white(const Position&p){if(p.remaining_board_plies()==0)return terminal(p);Value v=ScoreUnit*(p.score(Color::White)-p.score(Color::Black));v+=12*(p.alive_count(Color::White)-p.alive_count(Color::Black));int rv=reserve(p);v+=inventory(p,Color::White,rv)-inventory(p,Color::Black,rv);for(int i=0;i<PieceCount;++i){auto id=PieceId(i);auto&pc=p.piece(id);if(!pc.alive())continue;int mob=2*first_mob(p,id)+second_mob(p,id)/2+int(reach(pc).normal)/20;v+=piece_color(id)==Color::White?mob:-mob;}return v;}Value evaluate(const Position&p){Value v=evaluate_white(p);return p.side_to_move()==Color::White?v:-v;}
}
