#include "movegen.h"
#include <array>
#include <cstdint>
#include <unordered_set>
namespace rpsc {namespace {
constexpr std::array<Direction,4> Dirs{Direction::North,Direction::South,Direction::East,Direction::West};
constexpr std::array<Direction,4> Opp{Direction::South,Direction::North,Direction::West,Direction::East};
struct StepTable{std::array<std::array<Square,4>,64> next{};StepTable(){for(int s=0;s<64;++s){for(int di=0;di<4;++di){int f=file_of(Square(s)),r=rank_of(Square(s));switch(Dirs[di]){case Direction::North:++r;break;case Direction::South:--r;break;case Direction::East:++f;break;case Direction::West:--f;break;}next[s][di]=valid_square(f,r)?make_square(f,r):NoSquare;}}}};const StepTable&steps(){static const StepTable t;return t;}
Orientation item_orientation(Orientation o,Item i){auto&t=OrientationTable::instance();return i==Item::RotateLeft?t.rotate_left(o):i==Item::RotateRight?t.rotate_right(o):o;}int item_distance(Orientation o,Item i){int n=base_roll_length(OrientationTable::instance().top_gesture(o));if(i==Item::StepShort)--n;if(i==Item::StepLong)++n;return n;}
void exhaustive_paths(const Position&p,PieceId id,Move&m,Square cur,int rem,bool has,Direction last,std::vector<Move>&out){if(rem==0){out.push_back(m);return;}bool final=rem==1;for(int di=0;di<4;++di){Direction d=Dirs[di];if(has&&d==Opp[int(last)])continue;Square n=steps().next[int(cur)][di];if(n==NoSquare||p.occupied(n,id))continue;if(final&&p.adjacent_enemies(n,p.side_to_move(),id)>=2)continue;m.path[m.path_length++]=n;exhaustive_paths(p,id,m,n,rem-1,true,d,out);--m.path_length;}}
void exhaustive_item(const Position&p,PieceId id,const PieceState&pc,Item item,Square push,std::vector<Move>&out){Move m;m.piece=id;m.item=item;m.push_to=push;m.path[0]=pc.square;m.path_length=1;Orientation o=item_orientation(pc.orientation,item);exhaustive_paths(p,id,m,item==Item::Push?push:pc.square,item_distance(o,item),false,Direction::North,out);}
std::uint32_t partial_index(Square s,Orientation o,int rem,bool has,Direction last){auto st=OrientationTable::instance().gesture_state_id(o);auto lc=has?unsigned(last):4u;return unsigned(s)|(unsigned(st)<<6)|(unsigned(rem)<<11)|(lc<<15);}
struct Scratch{static constexpr std::size_t FinalSize=1u<<14,Mask=FinalSize-1;std::array<std::uint32_t,1u<<18>partial{};std::uint32_t pg=1;std::array<Key,FinalSize>keys{};std::array<std::uint32_t,FinalSize>marks{};std::uint32_t fg=1;std::uint32_t nextp(){if(++pg==0){partial.fill(0);pg=1;}return pg;}std::uint32_t nextf(){if(++fg==0){marks.fill(0);fg=1;}return fg;}bool insert(Key k,std::uint32_t g){std::size_t s=std::size_t((k*11400714819323198485ULL)>>50)&Mask;for(std::size_t q=0;q<FinalSize;++q){if(marks[s]!=g){marks[s]=g;keys[s]=k;return true;}if(keys[s]==k)return false;s=(s+1)&Mask;}return true;}};Scratch&scratch(){static thread_local Scratch s;return s;}
struct Gen{Position&p;Color mover,opp;int own_before,opp_before;bool tactical;Scratch&s;std::uint32_t pg=0,fg=0;std::vector<SearchMove>out;};
void emit(Gen&g,Move&m,Square cur,Orientation o){if(g.tactical){if(g.p.adjacent_enemies(cur,g.mover,m.piece)!=1)return;auto e=g.p.single_adjacent_enemy(cur,g.mover,m.piece);auto&t=OrientationTable::instance();Gesture a=t.top_gesture(o),b=t.top_gesture(g.p.piece(e).orientation);if(a==b)return;}UndoState u;g.p.do_move(m,u);Key k=g.p.search_key();int swing=(g.p.captures(g.mover)-g.own_before)-(g.p.captures(g.opp)-g.opp_before);g.p.undo_move(u);if(g.tactical&&swing==0)return;if(g.s.insert(k,g.fg))g.out.push_back({m,swing});}
void reduced_paths(Gen&g,PieceId id,Move&m,Square cur,Orientation o,int rem,bool has,Direction last){if(rem==0){emit(g,m,cur,o);return;}bool final=rem==1;auto&t=OrientationTable::instance();for(int di=0;di<4;++di){Direction d=Dirs[di];if(has&&d==Opp[int(last)])continue;Square n=steps().next[int(cur)][di];if(n==NoSquare||g.p.occupied(n,id))continue;if(final&&g.p.adjacent_enemies(n,g.mover,id)>=2)continue;Orientation no=t.roll(o,d);auto idx=partial_index(n,no,rem-1,true,d);if(g.s.partial[idx]==g.pg)continue;g.s.partial[idx]=g.pg;m.path[m.path_length++]=n;reduced_paths(g,id,m,n,no,rem-1,true,d);--m.path_length;}}
void reduced_item(Gen&g,PieceId id,const PieceState&pc,Item item,Square push){Move m;m.piece=id;m.item=item;m.push_to=push;m.path[0]=pc.square;m.path_length=1;Orientation o=item_orientation(pc.orientation,item);int d=item_distance(o,item);Square start=item==Item::Push?push:pc.square;g.pg=g.s.nextp();auto idx=partial_index(start,o,d,false,Direction::North);g.s.partial[idx]=g.pg;reduced_paths(g,id,m,start,o,d,false,Direction::North);}
std::vector<SearchMove> generate_search_internal(Position&p,bool tactical){Color mover=p.side_to_move();Gen g{p,mover,opposite(mover),p.captures(mover),p.captures(opposite(mover)),tactical,scratch(),0,0,{}};g.fg=g.s.nextf();g.out.reserve(512);for(int i=0;i<PieceCount;++i){auto id=PieceId(i);auto&pc=p.piece(id);if(!pc.alive()||piece_color(id)!=mover)continue;reduced_item(g,id,pc,Item::None,NoSquare);if(p.item_count(mover,0)>0)for(int di=0;di<4;++di){Square ps=steps().next[int(pc.square)][di];if(ps!=NoSquare&&!p.occupied(ps,id))reduced_item(g,id,pc,Item::Push,ps);}if(p.item_count(mover,1)>0){reduced_item(g,id,pc,Item::RotateLeft,NoSquare);reduced_item(g,id,pc,Item::RotateRight,NoSquare);}if(p.item_count(mover,2)>0){reduced_item(g,id,pc,Item::StepShort,NoSquare);reduced_item(g,id,pc,Item::StepLong,NoSquare);}}return g.out;}
}
std::vector<Move>generate_legal_moves(const Position&p){std::vector<Move>out;out.reserve(1536);for(int i=0;i<PieceCount;++i){auto id=PieceId(i);auto&pc=p.piece(id);if(!pc.alive()||piece_color(id)!=p.side_to_move())continue;exhaustive_item(p,id,pc,Item::None,NoSquare,out);if(p.item_count(p.side_to_move(),0)>0)for(int di=0;di<4;++di){Square ps=steps().next[int(pc.square)][di];if(ps!=NoSquare&&!p.occupied(ps,id))exhaustive_item(p,id,pc,Item::Push,ps,out);}if(p.item_count(p.side_to_move(),1)>0){exhaustive_item(p,id,pc,Item::RotateLeft,NoSquare,out);exhaustive_item(p,id,pc,Item::RotateRight,NoSquare,out);}if(p.item_count(p.side_to_move(),2)>0){exhaustive_item(p,id,pc,Item::StepShort,NoSquare,out);exhaustive_item(p,id,pc,Item::StepLong,NoSquare,out);}}return out;}
std::vector<Move>generate_unique_moves(Position&p){auto all=generate_legal_moves(p);std::vector<Move>u;u.reserve(all.size());std::unordered_set<Key>seen;seen.reserve(all.size()*2);for(auto&m:all){UndoState s;p.do_move(m,s);Key k=p.key();p.undo_move(s);if(seen.insert(k).second)u.push_back(m);}return u;}
std::vector<SearchMove>generate_search_moves_info(Position&p){return generate_search_internal(p,false);}std::vector<SearchMove>generate_tactical_moves_info(Position&p){return generate_search_internal(p,true);}std::vector<Move>generate_search_moves(Position&p){auto x=generate_search_moves_info(p);std::vector<Move>m;m.reserve(x.size());for(auto&e:x)m.push_back(e.move);return m;}
}
