#include "position.h"
#include <cmath>
#include <sstream>
#include <stdexcept>
namespace rpsc {namespace {
Direction direction_between(Square a,Square b){int dx=file_of(b)-file_of(a),dy=rank_of(b)-rank_of(a);if(dx==0&&dy==1)return Direction::North;if(dx==0&&dy==-1)return Direction::South;if(dx==1&&dy==0)return Direction::East;if(dx==-1&&dy==0)return Direction::West;throw std::invalid_argument("non-orthogonal step");}
Direction opposite_dir(Direction d){return d==Direction::North?Direction::South:d==Direction::South?Direction::North:d==Direction::East?Direction::West:Direction::East;}
bool adjacent(Square a,Square b){return std::abs(file_of(a)-file_of(b))+std::abs(rank_of(a)-rank_of(b))==1;}
int combat(Gesture a,Gesture b){if(a==b)return 0;if((a==Gesture::Scissors&&b==Gesture::Paper)||(a==Gesture::Rock&&b==Gesture::Scissors)||(a==Gesture::Paper&&b==Gesture::Rock))return 1;return-1;}
std::uint64_t mix(std::uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}
Orientation item_orientation(Orientation o,Item i){auto&t=OrientationTable::instance();return i==Item::RotateLeft?t.rotate_left(o):i==Item::RotateRight?t.rotate_right(o):o;}int required_rolls(Orientation o,Item i){int n=base_roll_length(OrientationTable::instance().top_gesture(o));if(i==Item::StepShort)--n;if(i==Item::StepLong)++n;return n;}}
Position::Position(){reset();}void Position::reset_pieces(){auto&t=OrientationTable::instance();pieces_[0]={make_square(0,0),t.canonical(Gesture::Scissors,WristDirection::South)};pieces_[1]={make_square(2,0),t.canonical(Gesture::Rock,WristDirection::South)};pieces_[2]={make_square(4,0),t.canonical(Gesture::Paper,WristDirection::South)};pieces_[3]={make_square(6,0),t.canonical(Gesture::Scissors,WristDirection::South)};pieces_[4]={make_square(7,7),t.canonical(Gesture::Scissors,WristDirection::North)};pieces_[5]={make_square(5,7),t.canonical(Gesture::Rock,WristDirection::North)};pieces_[6]={make_square(3,7),t.canonical(Gesture::Paper,WristDirection::North)};pieces_[7]={make_square(1,7),t.canonical(Gesture::Scissors,WristDirection::North)};}
void Position::reset(){reset_pieces();side_to_move_=Color::White;captures_white_=captures_black_=0;items_={};quiz_white_=quiz_black_=0;remaining_board_plies_=-1;}
bool Position::occupied(Square s,PieceId ex)const{for(int i=0;i<PieceCount;++i)if(i!=piece_index(ex)&&pieces_[i].alive()&&pieces_[i].square==s)return true;return false;}
int Position::adjacent_enemies(Square s,Color side,PieceId ex)const{int c=0;for(int i=0;i<PieceCount;++i){auto id=PieceId(i);if(id==ex||!pieces_[i].alive()||piece_color(id)==side)continue;if(adjacent(s,pieces_[i].square))++c;}return c;}
PieceId Position::single_adjacent_enemy(Square s,Color side,PieceId ex)const{PieceId found=PieceId::W1;int c=0;for(int i=0;i<PieceCount;++i){auto id=PieceId(i);if(id==ex||!pieces_[i].alive()||piece_color(id)==side)continue;if(adjacent(s,pieces_[i].square)){found=id;++c;}}if(c!=1)throw std::logic_error("expected one enemy");return found;}
int Position::alive_count(Color side)const{int c=0;for(int i=0;i<PieceCount;++i)if(pieces_[i].alive()&&piece_color(PieceId(i))==side)++c;return c;}
bool Position::is_legal_path(const Move&m)const{auto id=m.piece;auto&p=piece(id);if(!p.alive()||piece_color(id)!=side_to_move_||m.path_length<2||m.from()!=p.square)return false;int bucket=item_bucket(m.item);if(bucket>=0&&item_count(side_to_move_,bucket)<=0)return false;if(m.item!=Item::Push&&m.push_to!=NoSquare)return false;Orientation o=item_orientation(p.orientation,m.item);if(m.roll_count()!=required_rolls(o,m.item))return false;Square from=m.from();if(m.item==Item::Push){if(m.push_to==NoSquare||!adjacent(m.from(),m.push_to)||occupied(m.push_to,id))return false;from=m.push_to;}Direction last=Direction::North;bool has=false;for(std::uint8_t i=1;i<m.path_length;++i){Direction d;try{d=direction_between(from,m.path[i]);}catch(...){return false;}if(has&&d==opposite_dir(last))return false;if(occupied(m.path[i],id))return false;if(i+1==m.path_length&&adjacent_enemies(m.path[i],side_to_move_,id)>=2)return false;o=OrientationTable::instance().roll(o,d);from=m.path[i];last=d;has=true;}return true;}
MoveOutcome Position::do_move(const Move&m,UndoState&u){if(!is_legal_path(m))throw std::invalid_argument("illegal RPSC move");u={pieces_,side_to_move_,captures_white_,captures_black_,items_,quiz_white_,quiz_black_,remaining_board_plies_};auto&mp=piece(m.piece);Color mover=side_to_move_;Orientation o=item_orientation(mp.orientation,m.item);Square from=m.item==Item::Push?m.push_to:m.from();int bucket=item_bucket(m.item);if(bucket>=0)--items_[color_index(mover)][bucket];for(std::uint8_t i=1;i<m.path_length;++i){auto d=direction_between(from,m.path[i]);o=OrientationTable::instance().roll(o,d);from=m.path[i];}mp.square=m.to();mp.orientation=o;MoveOutcome out;if(adjacent_enemies(mp.square,mover,m.piece)==1){auto eid=single_adjacent_enemy(mp.square,mover,m.piece);auto&t=OrientationTable::instance();int r=combat(t.top_gesture(mp.orientation),t.top_gesture(piece(eid).orientation));if(r){out.has_capture=true;out.captured=r>0?eid:m.piece;Color winner=r>0?mover:opposite(mover);piece(out.captured).square=NoSquare;if(winner==Color::White)++captures_white_;else++captures_black_;}}
if(alive_count(Color::White)==0||alive_count(Color::Black)==0){reset_pieces();out.reset=true;}side_to_move_=opposite(side_to_move_);if(remaining_board_plies_>0)--remaining_board_plies_;return out;}
void Position::undo_move(const UndoState&u){pieces_=u.pieces;side_to_move_=u.side_to_move;captures_white_=u.captures_white;captures_black_=u.captures_black;items_=u.items;quiz_white_=u.quiz_white;quiz_black_=u.quiz_black;remaining_board_plies_=u.remaining_board_plies;}
Key Position::key()const{Key k=0;for(int i=0;i<PieceCount;++i){auto&p=pieces_[i];std::uint64_t sq=p.alive()?unsigned(p.square):64u;std::uint64_t f=(std::uint64_t(i)*65u+sq)*24u+p.orientation;k^=mix(0x123456789abcdef0ULL+f);}if(side_to_move_==Color::Black)k^=mix(0x3141592653589793ULL);k^=mix(0x1111000000000000ULL+unsigned(captures_white_));k^=mix(0x2222000000000000ULL+unsigned(captures_black_));k^=mix(0x2323000000000000ULL+unsigned(quiz_white_));k^=mix(0x2424000000000000ULL+unsigned(quiz_black_));k^=mix(0x2525000000000000ULL+unsigned(remaining_board_plies_+1));for(int s=0;s<2;++s)for(int b=0;b<3;++b)k^=mix(0x5555000000000000ULL+std::uint64_t(s*3+b)*0x10000ULL+unsigned(items_[s][b]));return k;}
Key Position::search_key()const{Key k=0;auto&t=OrientationTable::instance();for(int i=0;i<PieceCount;++i){auto&p=pieces_[i];std::uint64_t sq=p.alive()?unsigned(p.square):64u;std::uint64_t st=t.gesture_state_id(p.orientation);std::uint64_t f=(std::uint64_t(i)*65u+sq)*32u+st;k^=mix(0xabcdef0123456789ULL+f);}if(side_to_move_==Color::Black)k^=mix(0x2718281828459045ULL);k^=mix(0x3333000000000000ULL+unsigned(captures_white_));k^=mix(0x4444000000000000ULL+unsigned(captures_black_));k^=mix(0x4545000000000000ULL+unsigned(quiz_white_));k^=mix(0x4646000000000000ULL+unsigned(quiz_black_));k^=mix(0x4747000000000000ULL+unsigned(remaining_board_plies_+1));for(int s=0;s<2;++s)for(int b=0;b<3;++b)k^=mix(0x7777000000000000ULL+std::uint64_t(s*3+b)*0x10000ULL+unsigned(items_[s][b]));return k;}
std::string Position::debug_string()const{std::ostringstream o;o<<(side_to_move_==Color::White?"White":"Black")<<" to move | captures "<<captures_white_<<'-'<<captures_black_<<" | quiz "<<quiz_white_<<'-'<<quiz_black_<<" | remaining plies "<<remaining_board_plies_<<'\n';return o.str();}
}
